export const enum RecommendationsTypesEnum {
    GET_RECOMMENDATIONS_REQUEST = 'DASHBOARD_RECOMMENDATIONS_GET_RECOMMENDATIONS_REQUEST',
	GET_RECOMMENDATIONS_SUCCESS = 'DASHBOARD_RECOMMENDATIONS_GET_RECOMMENDATIONS_SUCCESS',
	GET_RECOMMENDATIONS_FAILURE = 'DASHBOARD_RECOMMENDATIONS_GET_RECOMMENDATIONS_FAILURE',
}
